'use client'
import {useState} from 'react'
type Invoice={id:string;doc_number:string;invoice_date:string;due_date:string|null;currency:string;total:number;balance:number}
const field={display:'block',width:'100%',padding:'10px 12px',marginTop:6,background:'#141414',border:'1px solid #444',borderRadius:6,color:'#fff'}
const button={padding:'9px 14px',border:'1px solid #444',borderRadius:6,background:'#262626',color:'#fff',cursor:'pointer'}
async function request(path:string,body?:unknown){const form=body instanceof FormData;const r=await fetch('/api/portal/admin/'+path,{method:body?'POST':'GET',headers:form?{}:{'Content-Type':'application/json'},body:body?(form?body:JSON.stringify(body)):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save invoice.');return d}
export default function InvoiceHistory({accountId,clientName}:{accountId:string;clientName:string}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<Invoice[]>([]),[loaded,setLoaded]=useState(false),[editing,setEditing]=useState<Invoice|null|undefined>(undefined),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[remove,setRemove]=useState<string|null>(null)
 async function load(){const d=await request('history?account_id='+accountId);setRows(d.invoices);setLoaded(true)}
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Request failed.')}finally{setBusy(false)}}
 return <div style={{borderTop:'1px solid #3a3a3a',marginTop:24,paddingTop:18}}>
 <button type="button" style={{...button,border:0,padding:0,background:'transparent',fontWeight:600}} aria-expanded={open} onClick={()=>{setOpen(!open);if(!open&&!loaded)action(load)}}>{open?'▾':'▸'} Historical invoices</button>
 {open&&<div style={{marginTop:16}}><p style={{color:'#aaa',fontSize:14,marginBottom:16}}>Add invoices from your previous billing account. They appear alongside synced invoices. Payment status is managed here.</p>
 {error&&<p role="alert" style={{color:'#ffac96',marginBottom:12}}>{error}</p>}{message&&<p role="status" style={{color:'#bce8cb',marginBottom:12}}>{message}</p>}
 {editing===undefined?<><button style={{...button,background:'#e03200',borderColor:'#e03200'}} disabled={busy||!loaded} onClick={()=>setEditing(null)}>+ Add historical invoice</button>
 {!loaded?<p style={{marginTop:16}}>Loading invoices…</p>:rows.length===0?<p style={{color:'#aaa',padding:'20px 0'}}>No historical invoices added yet.</p>:<div style={{overflowX:'auto',marginTop:16}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:14}}><thead><tr>{['Invoice','Issued','Amount','Status',''].map(t=><th key={t} style={{textAlign:'left',padding:10,color:'#aaa'}}>{t}</th>)}</tr></thead><tbody>{rows.map(i=><tr key={i.id} style={{borderTop:'1px solid #333'}}><td style={{padding:10}}>{i.doc_number}</td><td style={{padding:10,whiteSpace:'nowrap'}}>{i.invoice_date}</td><td style={{padding:10,whiteSpace:'nowrap'}}>{new Intl.NumberFormat('en-US',{style:'currency',currency:i.currency}).format(i.total)}</td><td style={{padding:10}}>{Number(i.balance)===0?'Paid':Number(i.balance)<Number(i.total)?'Partially paid':'Unpaid'}</td><td style={{padding:10}}><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button style={button} disabled={busy} onClick={()=>action(async()=>{const d=await request('history-download',{account_id:accountId,id:i.id});window.location.assign(d.url)})}>PDF ↓</button><button style={button} disabled={busy} onClick={()=>{setEditing(i);setMessage('')}}>Edit</button><button style={button} disabled={busy} onClick={()=>setRemove(i.id)}>Remove</button></div>{remove===i.id&&<div style={{marginTop:12}}><p>Remove this invoice from {clientName}’s portal?</p><button style={button} disabled={busy} onClick={()=>action(async()=>{await request('history-update',{account_id:accountId,id:i.id,remove:true});await load();setRemove(null);setMessage('Invoice removed from the portal.')})}>Confirm removal</button> <button style={button} disabled={busy} onClick={()=>setRemove(null)}>Cancel</button></div>}</td></tr>)}</tbody></table></div>}</>:<InvoiceForm key={editing?.id||'new'} invoice={editing} busy={busy} cancel={()=>{setEditing(undefined);setError('')}} submit={form=>action(async()=>{form.set('account_id',accountId);if(editing)await request('history-update',{...Object.fromEntries(form.entries()),id:editing.id});else await request('history-upload',form);setEditing(undefined);await load();setMessage(editing?'Invoice updated.':'Invoice added to the creator’s history.')})}/>}
 </div>}</div>
}
function InvoiceForm({invoice,busy,cancel,submit}:{invoice:Invoice|null;busy:boolean;cancel:()=>void;submit:(f:FormData)=>void}){
 const [paid,setPaid]=useState(!invoice||Number(invoice.balance)===0),[fileError,setFileError]=useState('')
 return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(paid)f.set('balance','0');submit(f)}} style={{padding:20,background:'#171717',border:'1px solid #3b3b3b',borderRadius:8}}>
 <h3 style={{fontWeight:600,marginBottom:16}}>{invoice?'Edit historical invoice':'Add historical invoice'}</h3>
 {!invoice&&<label style={{display:'block',marginBottom:20}}>Invoice PDF <span style={{color:'#aaa',fontSize:13}}>· Up to 3 MB</span><input name="file" type="file" accept="application/pdf,.pdf" required disabled={busy} style={field} onChange={e=>{const f=e.target.files?.[0];const invalid=!!f&&f.size>3145728;setFileError(invalid?'Choose a PDF smaller than 3 MB.':'');e.target.setCustomValidity(invalid?'PDF must be smaller than 3 MB.':'')}}/>{fileError&&<span role="alert" style={{color:'#ffac96'}}>{fileError}</span>}</label>}
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:16}}>
 <label>Invoice number<input name="doc_number" required maxLength={80} defaultValue={invoice?.doc_number} placeholder="INV-001" style={field} disabled={busy}/></label>
 <label>Issue date<input name="invoice_date" type="date" required defaultValue={invoice?.invoice_date} style={field} disabled={busy}/></label>
 <label>Due date <span style={{color:'#aaa'}}>(optional)</span><input name="due_date" type="date" defaultValue={invoice?.due_date||''} style={field} disabled={busy}/></label>
 <label>Total amount<input name="total" type="number" min="0.01" max="999999999999.99" step="0.01" required defaultValue={invoice?.total} placeholder="0.00" style={field} disabled={busy}/></label>
 <label>Currency<input name="currency" list="invoice-currencies" required pattern="[A-Za-z]{3}" maxLength={3} defaultValue={invoice?.currency||'USD'} style={field} disabled={busy}/><datalist id="invoice-currencies"><option value="USD"/><option value="CAD"/><option value="EUR"/><option value="GBP"/></datalist></label>
 <label>Payment status<select value={paid?'paid':'unpaid'} onChange={e=>setPaid(e.target.value==='paid')} style={field} disabled={busy}><option value="paid">Paid</option><option value="unpaid">Unpaid / partially paid</option></select></label>
 {!paid&&<label>Remaining balance<input name="balance" type="number" min="0" step="0.01" required defaultValue={invoice?.balance||''} placeholder="Amount still owed" style={field} disabled={busy}/></label>}
 </div><p style={{fontSize:13,color:'#aaa',margin:'16px 0'}}>Confirm these details match the PDF. Historical invoices are not updated by QuickBooks sync.</p>
 <button style={{...button,background:'#e03200',borderColor:'#e03200'}} disabled={busy}>{busy?'Saving…':invoice?'Save changes':'Upload invoice'}</button> <button type="button" style={button} disabled={busy} onClick={cancel}>Cancel</button>
 </form>
}
