'use client'
import {useState,useEffect,useRef,useId} from 'react'
import {Collapse,SkeletonRows} from './portal-ux'
type Invoice={id:string;doc_number:string;invoice_date:string;due_date:string|null;currency:string;total:number;balance:number}
const field={display:'block',width:'100%',padding:'10px 12px',marginTop:6,background:'#141414',border:'1px solid #444',borderRadius:6,color:'#fff'}
const button={padding:'9px 14px',border:'1px solid #444',borderRadius:6,background:'#262626',color:'#fff',cursor:'pointer'}
async function request(path:string,body?:unknown){const form=body instanceof FormData;const r=await fetch('/api/portal/admin/'+path,{method:body?'POST':'GET',headers:form?{}:{'Content-Type':'application/json'},body:body?(form?body:JSON.stringify(body)):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save invoice.');return d}
function upload(path:string,body:FormData,progress:(n:number)=>void){return new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/portal/admin/'+path);xhr.timeout=120000;xhr.upload.onprogress=e=>{if(e.lengthComputable)progress(Math.round(e.loaded/e.total*100))};xhr.onload=()=>{let d;try{d=JSON.parse(xhr.responseText)}catch{reject(new Error('Unexpected server response. Refresh invoice history before retrying.'));return}if(xhr.status>=200&&xhr.status<300)resolve();else reject(new Error(d.error||'Unable to save invoice.'))};xhr.onerror=xhr.ontimeout=()=>reject(new Error('Connection interrupted. Check invoice history before retrying.'));xhr.send(body)})}
export default function InvoiceHistory({accountId,clientName}:{accountId:string;clientName:string}){
 const actionLock=useRef(false)
 const [progress,setProgress]=useState<number|null>(null)
 const [open,setOpen]=useState(false),[rows,setRows]=useState<Invoice[]>([]),[loaded,setLoaded]=useState(false),[editing,setEditing]=useState<Invoice|null|undefined>(undefined),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[remove,setRemove]=useState<string|null>(null)
 async function load(){const d=await request('history?account_id='+accountId);setRows(d.invoices);setLoaded(true)}
 async function action(fn:()=>Promise<void>){if(actionLock.current)return;actionLock.current=true;setBusy(true);setError('');setMessage('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Request failed.')}finally{actionLock.current=false;setBusy(false);setProgress(null)}}
 return <div style={{borderTop:'1px solid #3a3a3a',marginTop:24,paddingTop:18}}>
 <button type="button" style={{...button,border:0,padding:0,background:'transparent',fontWeight:600}} aria-expanded={open} onClick={()=>{setOpen(!open);if(!open&&!loaded)action(load)}}>{open?'▾':'▸'} Manual invoices</button>
 <Collapse open={open}><div style={{marginTop:16}}><p style={{color:'#aaa',fontSize:14,marginBottom:16}}>Upload an invoice or monthly breakdown at any time. Manage its details and payment status here.</p>
 {error&&<p role="alert" style={{color:'#ffac96',marginBottom:12}}>{error}</p>}{message&&<p role="status" style={{color:'#bce8cb',marginBottom:12}}>{message}</p>}
 {editing===undefined?<><button style={{...button,background:'#e03200',borderColor:'#e03200'}} disabled={busy||!loaded} onClick={()=>setEditing(null)}>+ Add manual invoice</button>
 {!loaded?<>{error?<button disabled={busy} onClick={()=>action(load)}>Retry loading invoices</button>:<SkeletonRows count={2}/>}</>:rows.length===0?<p style={{color:'#aaa',padding:'20px 0'}}>No manual invoices added yet.</p>:<div style={{overflowX:'auto',marginTop:16}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:14}}><thead><tr>{['Invoice','Issued','Amount','Status',''].map(t=><th key={t} style={{textAlign:'left',padding:10,color:'#aaa'}}>{t}</th>)}</tr></thead><tbody>{rows.map(i=><tr key={i.id} style={{borderTop:'1px solid #333'}}><td style={{padding:10}}>{i.doc_number}</td><td style={{padding:10,whiteSpace:'nowrap'}}>{i.invoice_date}</td><td style={{padding:10,whiteSpace:'nowrap'}}>{new Intl.NumberFormat('en-US',{style:'currency',currency:i.currency}).format(i.total)}</td><td style={{padding:10}}>{Number(i.balance)===0?'Paid':Number(i.balance)<Number(i.total)?'Partially paid':'Unpaid'}</td><td style={{padding:10}}><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button style={button} disabled={busy} onClick={()=>action(async()=>{const d=await request('history-download',{account_id:accountId,id:i.id});window.location.assign(d.url)})}>Download ↓</button><button style={button} disabled={busy} onClick={()=>{setEditing(i);setMessage('')}}>Edit</button><button style={button} disabled={busy} onClick={()=>setRemove(i.id)}>Remove</button></div>{remove===i.id&&<div style={{marginTop:12}}><p>Remove this invoice from {clientName}’s portal?</p><button style={button} disabled={busy} onClick={()=>action(async()=>{await request('history-update',{account_id:accountId,id:i.id,remove:true});await load();setRemove(null);setMessage('Invoice removed from the portal.')})}>Confirm removal</button> <button style={button} disabled={busy} onClick={()=>setRemove(null)}>Cancel</button></div>}</td></tr>)}</tbody></table></div>}</>:<InvoiceForm key={editing?.id||'new'} invoice={editing} busy={busy} progress={progress} cancel={()=>{setEditing(undefined);setError('')}} submit={form=>action(async()=>{form.set('account_id',accountId);if(editing){form.set('id',editing.id);setProgress(0);await upload('history-replace',form,setProgress)}else {setProgress(0);await upload('history-upload',form,setProgress)}setProgress(null);setEditing(undefined);setMessage(editing?'Invoice updated.':'Invoice added to the creator’s history.');try{await load()}catch{setError('Invoice saved, but the list could not refresh. Reopen this page to see it.')} })}/>}
 </div></Collapse></div>
}
function InvoiceForm({invoice,busy,progress,cancel,submit}:{invoice:Invoice|null;busy:boolean;progress:number|null;cancel:()=>void;submit:(f:FormData)=>void}){
 const currencyId=useId(),inputRef=useRef<HTMLInputElement>(null)
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[dragging,setDragging]=useState(false),[balanceError,setBalanceError]=useState('')
 useEffect(()=>{if(!file||!file.type.startsWith('image/')){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file])
 function choose(f:File|undefined){if(!f)return;const error=f.size>3145728?'Choose a file smaller than 3 MB.':!['application/pdf','image/jpeg','image/png'].includes(f.type)?'Choose a PDF, JPG or PNG file.':'';setFileError(error);setFile(error?null:f);if(inputRef.current)inputRef.current.value=''}
 const [paid,setPaid]=useState(!invoice||Number(invoice.balance)===0),[fileError,setFileError]=useState('')
 return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!file&&!invoice){setFileError('Choose an invoice attachment.');inputRef.current?.focus();return}if(file)f.set('file',file);if(paid)f.set('balance','0');if(Number(f.get('balance'))>Number(f.get('total'))){setBalanceError('Remaining balance cannot exceed the total.');e.currentTarget.querySelector<HTMLInputElement>('[name=balance]')?.focus();return}setBalanceError('');submit(f)}} style={{padding:20,background:'#171717',border:'1px solid #3b3b3b',borderRadius:8}}>
 <h3 style={{fontWeight:600,marginBottom:16}}>{invoice?'Edit manual invoice':'Add manual invoice'}</h3>
 <div className="portal-upload" data-dragging={dragging} onDragOver={e=>{e.preventDefault();if(!busy)setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(!busy)choose(e.dataTransfer.files[0])}}>
 <label>{invoice?'Replace attachment (optional)':'Invoice or monthly breakdown'}<span>Drop a file here or choose a file · PDF, JPG, PNG · Up to 3 MB</span><input ref={inputRef} type="file" accept="application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png" disabled={busy} onChange={e=>choose(e.target.files?.[0])}/></label>
 {file&&<div className="portal-file-card">{preview&&<img src={preview} alt="Selected invoice attachment preview"/>}<div><strong>{file.name}</strong><small>{(file.size/1024).toFixed(0)} KB · Ready to upload</small></div><button type="button" disabled={busy} onClick={()=>{setFile(null);setFileError('')}}>Remove</button></div>}
 {fileError&&<p role="alert" className="portal-error">{fileError}</p>}
 {busy&&progress!==null&&<div role="status"><progress max={100} value={progress}/><span>{progress<100?`Uploading ${progress}%`:'Upload received. Saving invoice…'}</span></div>}
 </div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:16}}>
 <label>Invoice number or billing label<input name="doc_number" required maxLength={80} defaultValue={invoice?.doc_number} placeholder="INV-001 or September 2026" style={field} disabled={busy}/></label>
 <label>Issue date<input name="invoice_date" type="date" required defaultValue={invoice?.invoice_date} style={field} disabled={busy}/></label>
 <label>Due date <span style={{color:'#aaa'}}>(optional)</span><input name="due_date" type="date" defaultValue={invoice?.due_date||''} style={field} disabled={busy}/></label>
 <label>Total amount<input name="total" type="number" min="0.01" max="999999999999.99" step="0.01" required defaultValue={invoice?.total} placeholder="0.00" style={field} disabled={busy}/></label>
 <label>Currency<input name="currency" list={currencyId} required pattern="[A-Za-z]{3}" maxLength={3} defaultValue={invoice?.currency||'USD'} style={field} disabled={busy}/><datalist id={currencyId}><option value="USD"/><option value="CAD"/><option value="EUR"/><option value="GBP"/></datalist></label>
 <label>Payment status<select value={paid?'paid':'unpaid'} onChange={e=>setPaid(e.target.value==='paid')} style={field} disabled={busy}><option value="paid">Paid</option><option value="unpaid">Unpaid / partially paid</option></select></label>
 {!paid&&<label>Remaining balance<input name="balance" type="number" min="0" step="0.01" required defaultValue={invoice?.balance||''} placeholder="Amount still owed" style={field} disabled={busy} aria-invalid={!!balanceError} onChange={()=>setBalanceError('')}/>{balanceError&&<span role="alert" className="portal-error">{balanceError}</span>}</label>}
 </div><p style={{fontSize:13,color:'#aaa',margin:'16px 0'}}>Confirm these details match the attachment. Manual invoices are not updated by QuickBooks sync.</p>
 <button style={{...button,background:'#e03200',borderColor:'#e03200'}} disabled={busy}>{busy?'Saving…':invoice?'Save changes':'Upload invoice'}</button> <button type="button" style={button} disabled={busy} onClick={cancel}>Cancel</button>
 </form>
}
