'use client'
import {useEffect,useState} from 'react'
import {ActionLabel,SkeletonRows,usePortalAction} from './portal-ux'
type Package={name:string;deliverables:string;amount:number;currency:string;frequency:string;visible:boolean}
const blank:Package={name:'',deliverables:'',amount:0,currency:'USD',frequency:'monthly',visible:false}
export default function PackageSettings({clientId}:{clientId:string}){
 const [value,setValue]=useState<Package|null>(null),[loadError,setLoadError]=useState('');const {busy,saved,error,message,run}=usePortalAction()
 async function load(){setLoadError('');try{const r=await fetch('/api/portal/admin/package?client_id='+encodeURIComponent(clientId));const d=await r.json();if(!r.ok)throw new Error(d.error);setValue(d.package||blank)}catch(e){setLoadError(e instanceof Error?e.message:'Unable to load package.')}}
 useEffect(()=>{void load()},[clientId])
 if(!value)return loadError?<div><p role="alert" className="portal-error">{loadError}</p><button onClick={load}>Retry</button></div>:<SkeletonRows count={2}/>
 const update=(patch:Partial<Package>)=>setValue({...value,...patch})
 return <form className="portal-package-form" onSubmit={e=>{e.preventDefault();run(async()=>{const r=await fetch('/api/portal/admin/package',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...value,client_id:clientId})});const d=await r.json();if(!r.ok)throw new Error(d.error)},'Package saved.')}}><p>This summary appears on the creator’s dashboard and My package page. It does not change invoices or payment amounts.</p><fieldset disabled={busy}><label>Package name<input required maxLength={120} value={value.name} onChange={e=>update({name:e.target.value})} placeholder="Monthly production"/></label><div className="portal-package-fields"><label>Amount<input type="number" required min="0" max="10000000" step="0.01" value={value.amount} onChange={e=>update({amount:Number(e.target.value)})}/></label><label>Currency<select value={value.currency} onChange={e=>update({currency:e.target.value})}>{['USD','CAD','EUR','GBP','AUD','MXN'].map(c=><option key={c}>{c}</option>)}</select></label><label>Billing frequency<select value={value.frequency} onChange={e=>update({frequency:e.target.value})}>{Object.entries({monthly:'Monthly',quarterly:'Quarterly',annually:'Annually',per_project:'Per project',custom:'As agreed'}).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label></div><label>Included deliverables<textarea rows={6} maxLength={4000} value={value.deliverables} onChange={e=>update({deliverables:e.target.value})} placeholder="One deliverable per line"/></label><label className="portal-project-check"><input type="checkbox" checked={value.visible} onChange={e=>update({visible:e.target.checked})}/> Show package in creator portal</label>{error&&<p className="portal-error" role="alert">{error}</p>}{message&&<p className="portal-success" role="status">{message}</p>}<button className="portal-primary"><ActionLabel busy={busy} saved={saved}>Save package</ActionLabel></button></fieldset></form>
}
