 'use client'
import { useEffect,useState } from 'react'
import InvoiceHistory from './invoice-history'
import './portal-admin.css'
type Client={id:string;label:string;active:boolean}
type Account={id:string;client_id:string;creator_user_id:string|null;qbo_customer_id:string|null;customer_name:string|null;enabled:boolean;payment_url?:string|null}
type Template={production_client_id:string;template_name:string;label:string}
type Link={production_client_id:string;template_name:string;portal_client_id:string}
type Data={environment:string;legacyAccounts:number;clients:Client[];accounts:Account[];templates:{client_id:string;template_name:string|null;clients:{label:string}|{label:string}[]}[];associations:Link[];missing:string[];sync:null|{state:string;last_success_at:string|null;last_error:string|null}}
const input={background:'#161616',border:'1px solid #444',borderRadius:6,padding:10,color:'white',width:'100%'}
const button={...input,width:'auto',marginRight:12}
const templateKey=(t:{production_client_id:string;template_name:string})=>JSON.stringify([t.production_client_id,t.template_name])
async function api(path:string,body?:unknown){const r=await fetch('/api/portal/admin/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error);return d}
export default function PortalAdmin(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[search,setSearch]=useState(''),[archived,setArchived]=useState(false),[adding,setAdding]=useState(false),[name,setName]=useState(''),[expanded,setExpanded]=useState<string|null>(null)
 async function load(){setData(await api('status'))}
 useEffect(()=>{const u=new URL(window.location.href);if(u.searchParams.has('connected'))setMessage('QuickBooks connected.');if(u.searchParams.has('connectionError'))setError('QuickBooks authorization did not complete.');u.searchParams.delete('connected');u.searchParams.delete('connectionError');window.history.replaceState(window.history.state,'',u.pathname+u.search+u.hash);load().catch(e=>setError(e.message))},[])
 async function run(fn:()=>Promise<void>,success='Changes saved.'){setBusy(true);setError('');setMessage('');try{await fn();setMessage(success)}catch(e){setError(e instanceof Error?e.message:'Request failed.')}finally{setBusy(false)}}
 const templates:Template[]=Array.from(new Map((data?.templates||[]).map(t=>{const group=Array.isArray(t.clients)?t.clients[0]:t.clients;const item={production_client_id:t.client_id,template_name:t.template_name||'Default',label:group?.label||'Production'};return [templateKey(item),item]})).values()).sort((a,b)=>(a.label+a.template_name).localeCompare(b.label+b.template_name))
 const visible=(data?.clients||[]).filter(c=>c.active!==archived&&c.label.toLowerCase().includes(search.toLowerCase()))
 return <main className="portal-workspace"><header className="portal-heading"><div><h1>Client portals</h1><p>Billing, access and production templates for each client.</p></div><button className="portal-primary" disabled={busy} onClick={()=>setAdding(!adding)}>+ Add client</button></header>
 {error&&<p className="portal-error" role="alert">{error}</p>}{message&&<p className="portal-success" role="status">{message}</p>}
 {adding&&<form className="portal-create" onSubmit={e=>{e.preventDefault();run(async()=>{const d=await api('client',{label:name});await load();setAdding(false);setName('');setArchived(false);setExpanded(d.id)},'Client created. Add billing details or associate templates below.')}}><label>Client name<input autoFocus required maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Walker America"/></label><button className="portal-primary" disabled={busy}>Create client</button><button type="button" disabled={busy} onClick={()=>setAdding(false)}>Cancel</button></form>}
 {!data?<p>{error?'Unable to load clients. Check setup and try refreshing.':'Loading clients…'}</p>:<><div className="portal-toolbar"><label className="portal-search"><span className="sr-only">Search clients</span><input placeholder="Search clients…" value={search} onChange={e=>setSearch(e.target.value)}/></label><button aria-pressed={!archived} onClick={()=>setArchived(false)}>Active ({data.clients.filter(c=>c.active).length})</button><button aria-pressed={archived} onClick={()=>setArchived(true)}>Archived ({data.clients.filter(c=>!c.active).length})</button></div>
 {!visible.length&&<div className="portal-empty">{search?'No matching clients.':archived?'No archived clients.':'No clients yet. Add a client to get started.'}</div>}
 {visible.map(c=>{const a=data.accounts.find(a=>a.client_id===c.id);return <section className="portal-client" key={c.id}><div className="portal-client-row"><button className="portal-client-toggle" aria-expanded={expanded===c.id} onClick={()=>setExpanded(expanded===c.id?null:c.id)}><span className="portal-chevron">{expanded===c.id?'▾':'▸'}</span><span><strong>{c.label}</strong><small>{a?.qbo_customer_id?'QuickBooks + manual billing':'Manual billing'} · {data.associations.filter(l=>l.portal_client_id===c.id).length} templates</small></span></button><span className="portal-badge">{!c.active?'Archived':a?.enabled?'Portal enabled':'Setup pending'}</span>{c.active&&a?.enabled&&<button disabled={busy} onClick={()=>run(async()=>{const d=await api('preview',{account_id:a.id});window.location.assign(d.url)},'')}>View as creator ↗</button>}</div>{expanded===c.id&&<ClientPanel key={c.id} client={c} account={a} templates={templates} data={data} busy={busy} run={run} load={load}/>}</section>})}
 <details className="portal-integrations"><summary>Integration settings <span>QuickBooks · {data.environment} · {data.sync?.state==='connected'?'Connected':'Not connected'}</span></summary><div><p>One company connection powers QuickBooks billing for all linked clients.</p><p>Last sync: {data.sync?.last_success_at?new Date(data.sync.last_success_at).toLocaleString():'Not synchronized'}</p>{data.sync?.last_error&&<p className="portal-error">{data.sync.last_error}</p>}{data.missing.length>0&&<p>Configuration needed: {data.missing.join(', ')}</p>}<button disabled={busy||data.sync?.state==='disconnect_pending'} onClick={()=>run(async()=>{const d=await api('qbo-connect',{});window.location.assign(d.url)},'')}>Connect / reconnect</button> <button disabled={busy||data.sync?.state!=='connected'} onClick={()=>run(async()=>{await api('sync',{});await load()},'Invoices synchronized.')}>Sync now</button> {data.sync&&data.sync.state!=='disconnected'&&<a href="/portal-admin/disconnect">Disconnect</a>}</div></details></>}
 <footer><a href="mailto:info@nillistudio.com">Support</a> · <a href="https://www.nillistudio.com/creator-portal/terms">Terms</a> · <a href="https://www.nillistudio.com/creator-portal/privacy">Privacy</a></footer></main>
}
function ClientPanel({client,account,templates,data,busy,run,load}:{client:Client;account?:Account;templates:Template[];data:Data;busy:boolean;run:(fn:()=>Promise<void>,success?:string)=>Promise<void>;load:()=>Promise<void>}){
 const [tab,setTab]=useState('Overview'),[label,setLabel]=useState(client.label),[confirm,setConfirm]=useState(false),[filter,setFilter]=useState(''),[selected,setSelected]=useState(()=>data.associations.filter(l=>l.portal_client_id===client.id).map(templateKey))
 return <div className="portal-client-body"><div className="portal-tabs" role="tablist" aria-label={`${client.label} settings`}>{['Overview','Billing','Templates','Access'].map(t=><button role="tab" aria-selected={tab===t} disabled={!client.active&&t!=='Overview'} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Overview'&&<div className="portal-overview"><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('client',{id:client.id,label});await load()})}}><label>Client name<input required maxLength={120} value={label} onChange={e=>setLabel(e.target.value)}/></label><button disabled={busy}>Save name</button></form><div className="portal-archive"><h3>{client.active?'Archive client':'Restore client'}</h3><p>{client.active?'Disable portal access and pause invoice synchronization. Invoice history and template links are retained.':'Restore this client, then explicitly enable portal access when ready.'}</p>{confirm?<><button disabled={busy} onClick={()=>run(async()=>{await api('client-active',{id:client.id,active:!client.active});await load();setConfirm(false)},client.active?'Client archived.':'Client restored. Portal access remains disabled.')}>Confirm {client.active?'archive':'restore'}</button> <button disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button></>:<button disabled={busy} onClick={()=>setConfirm(true)}>{client.active?'Archive client':'Restore client'}</button>}</div></div>}
 {client.active&&<AccountForm key={account?.id||'new'} tab={tab} client={client} account={account} busy={busy} connected={data.sync?.state==='connected'} save={b=>run(async()=>{await api('account',b);await load()})} preview={id=>run(async()=>{const d=await api('preview',{account_id:id});window.location.assign(d.url)},'')}/>}
 {tab==='Templates'&&<div><p>Associate workflows with this client. Unassigned templates can remain internal. This does not move existing production work.</p><input aria-label="Search templates" placeholder="Search production templates…" value={filter} onChange={e=>setFilter(e.target.value)}/><div className="portal-template-list">{templates.filter(t=>(t.label+' '+t.template_name).toLowerCase().includes(filter.toLowerCase())).map(t=>{const key=templateKey(t),link=data.associations.find(l=>templateKey(l)===key),other=link&&link.portal_client_id!==client.id;return <label key={key}><input type="checkbox" checked={selected.includes(key)} disabled={busy||!!other} onChange={e=>setSelected(e.target.checked?[...selected,key]:selected.filter(k=>k!==key))}/><span>{t.label}<small>{t.template_name}{other?' · Assigned to '+data.clients.find(c=>c.id===link.portal_client_id)?.label:''}</small></span></label>})}{!templates.length&&<p>No production templates available.</p>}</div><button className="portal-primary" disabled={busy} onClick={()=>run(async()=>{await api('client-templates',{id:client.id,templates:templates.filter(t=>selected.includes(templateKey(t))).map(({production_client_id,template_name})=>({production_client_id,template_name}))});await load()},'Template associations saved.')}>Save template associations</button></div>}
 </div>
}
function AccountForm({client,account,busy,connected,save,preview,tab}:{tab:string;client:Client;account?:Account;busy:boolean;connected:boolean;save:(b:unknown)=>void;preview:(id:string)=>void}){
 const [user,setUser]=useState(account?.creator_user_id||''),[customer,setCustomer]=useState(account?.qbo_customer_id||''),[enabled,setEnabled]=useState(account?.enabled||false),[payment,setPayment]=useState(account?.payment_url||''),[name,setName]=useState(account?.customer_name||''),[confirmed,setConfirmed]=useState(!!account?.customer_name),[checking,setChecking]=useState(false),[error,setError]=useState('')
 async function verify(){setChecking(true);setError('');setName('');setConfirmed(false);try{const d=await api('customer-check',{customer_id:customer});setName(d.name)}catch(e){setError(e instanceof Error?e.message:'Unable to verify customer.')}finally{setChecking(false)}}
 return <section style={{display:tab==='Billing'||tab==='Access'?'block':'none'}}>

 <form onSubmit={e=>{e.preventDefault();save({client_id:client.id,creator_user_id:user,qbo_customer_id:customer,customer_confirmation:confirmed?name:null,enabled,payment_url:payment})}}>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:16}}>
 <label style={{display:tab==='Access'?'block':'none'}}>Creator auth user ID<input style={input} value={user} onChange={e=>setUser(e.target.value)} placeholder="Separate creator-auth project UUID"/></label>
 <label style={{display:tab==='Billing'?'block':'none'}}>QuickBooks customer ID (optional)<input style={input} value={customer} disabled={!!account?.qbo_customer_id||checking} onChange={e=>{setCustomer(e.target.value);setName('');setConfirmed(false)}} pattern="[0-9]*" placeholder="Leave blank for manual billing"/></label>
 </div>
 {tab==='Billing'&&!account?.customer_name&&<button type="button" style={{...button,marginTop:12}} disabled={!connected||busy||checking||!customer} onClick={verify}>{checking?'Checking…':'Verify customer'}</button>}
 {tab==='Billing'&&name&&<label style={{display:'block',margin:'16px 0'}}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I confirm “{name}” is the QuickBooks customer for {client.label}.</label>}
 {error&&<p role="alert">{error}</p>}
 <label style={{display:tab==='Billing'?'block':'none',marginTop:16}}>Payment link (optional)<input type="url" style={input} value={payment} onChange={e=>setPayment(e.target.value)} placeholder="https://…" maxLength={2048}/></label>
 <label style={{display:tab==='Access'?'block':'none',margin:'16px 0'}}><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enable creator portal</label>
 <button disabled={busy||checking||!!customer&&!confirmed} style={{...button,background:'#e03200'}}>Save account</button>
 {account?.enabled&&<button type="button" disabled={busy} style={button} onClick={()=>preview(account.id)}>View as creator ↗</button>}
 </form>{account&&tab==='Billing'&&<InvoiceHistory accountId={account.id} clientName={client.label}/>}</section>
}
