'use client'
import { useEffect,useState } from 'react'
type Client={id:string;label:string}
type Account={id:string;client_id:string;creator_user_id:string|null;qbo_customer_id:string|null;enabled:boolean}
type Data={clients:Client[];accounts:Account[];missing:string[];sync:null|{last_success_at:string|null;last_error:string|null;dirty_version:number;synced_version:number}}
const input={background:'#1e1e1e',border:'1px solid #444',borderRadius:6,padding:10,color:'white',width:'100%'}
export default function PortalAdmin(){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function api(path:string,body?:unknown){const r=await fetch('/api/portal/admin/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error);return d}
 async function load(){setData(await api('status'))}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Request failed.')}finally{setBusy(false)}}
 return <div style={{padding:32,maxWidth:1100}}><h1 style={{fontSize:28,fontWeight:700}}>Creator portals</h1><p style={{color:'#aaa',margin:'12px 0 24px'}}>Connect each client once. Invoices update from QuickBooks automatically after setup.</p>{error&&<p role="alert" style={{color:'#ff9a7b',margin:16}}>{error}</p>}{!data?<p>Portal setup is required if this screen cannot load. Apply the creator portal migration first.</p>:<><section style={{padding:24,background:'#1e1e1e',borderRadius:12,marginBottom:24}}><h2>QuickBooks synchronization</h2><p style={{margin:'12px 0'}}>Last successful sync: {data.sync?.last_success_at?new Date(data.sync.last_success_at).toLocaleString():'Not synchronized'}</p>{data.sync?.last_error&&<p role="alert">{data.sync.last_error}</p>}{data.sync&&data.sync.dirty_version!==data.sync.synced_version&&<p>Updates waiting for the next sync.</p>}{data.missing.length>0&&<p style={{color:'#ff9a7b',marginBottom:12}}>Configuration needed: {data.missing.join(', ')}</p>}<button disabled={busy} style={{...input,width:'auto',marginRight:12}} onClick={()=>run(async()=>{const d=await api('qbo-connect',{});window.location.assign(d.url)})}>Connect QuickBooks</button><button disabled={busy||!data.sync} style={{...input,width:'auto'}} onClick={()=>run(async()=>{await api('sync',{});await load()})}>Sync now</button></section>{data.clients.map(c=><AccountForm key={c.id} client={c} account={data.accounts.find(a=>a.client_id===c.id)} busy={busy} save={b=>run(async()=>{await api('account',b);await load()})} preview={id=>run(async()=>{const d=await api('preview',{account_id:id});window.location.assign(d.url)})}/>)}</>}</div>
}
function AccountForm({client,account,busy,save,preview}:{client:Client;account?:Account;busy:boolean;save:(b:unknown)=>void;preview:(id:string)=>void}){const [user,setUser]=useState(account?.creator_user_id||''),[customer,setCustomer]=useState(account?.qbo_customer_id||''),[enabled,setEnabled]=useState(account?.enabled||false);return <section style={{border:'1px solid #333',padding:24,borderRadius:12,marginBottom:20}}><h2 style={{fontSize:20,marginBottom:16}}>{client.label}</h2><form onSubmit={e=>{e.preventDefault();save({client_id:client.id,creator_user_id:user,qbo_customer_id:customer,enabled})}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:16}}><label>Creator auth user ID<input style={input} value={user} onChange={e=>setUser(e.target.value)} placeholder="Separate creator-auth project UUID"/></label><label>QuickBooks customer ID<input style={input} value={customer} onChange={e=>setCustomer(e.target.value)} pattern="[0-9]*" placeholder="Verified QBO customer ID"/></label></div><label style={{display:'block',margin:'16px 0'}}><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enable creator portal</label><button disabled={busy} style={{...input,width:'auto',background:'#e03200'}}>Save account</button>{account?.enabled&&<button type="button" disabled={busy} style={{...input,width:'auto',marginLeft:12}} onClick={()=>preview(account.id)}>View as creator ↗</button>}</form></section>}
