'use client'
import {useEffect,useState,useRef} from 'react'
import {ActionLabel,SkeletonRows,usePortalAction} from './portal-ux'
type Project={id:string;title:string;format:string;release_date:string;review_url:string|null;review_ready:boolean;publication_url:string|null;published_at:string|null;status:string}
async function request(clientId:string,body?:unknown,offset=0){const r=await fetch('/api/portal/admin/production?client_id='+encodeURIComponent(clientId)+'&offset='+offset,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load projects.');return d}
export default function ProjectSettings({clientId,active}:{clientId:string;active:boolean}){
 const count=useRef(24),lock=useRef(false)
 const [projects,setProjects]=useState<Project[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[next,setNext]=useState<number|null>(null),[loading,setLoading]=useState(false)
 async function load(offset=0){if(lock.current)return;lock.current=true;setLoading(true);setError('');try{const d=await request(clientId,undefined,offset);setProjects(p=>offset?[...p,...d.projects]:d.projects);count.current=offset+d.projects.length;setNext(d.nextOffset);setLoaded(true)}catch(e){setError(e instanceof Error?e.message:'Unable to load projects.')}finally{lock.current=false;setLoading(false)}}
 useEffect(()=>{void load()},[clientId])
 useEffect(()=>{if(!active)return;let stopped=false;async function refresh(){if(document.hidden||lock.current)return;lock.current=true;try{let rows:Project[]=[];let nextOffset:number|null=0;while(nextOffset!==null&&rows.length<Math.max(count.current,24)){const d=await request(clientId,undefined,nextOffset);rows.push(...d.projects);nextOffset=d.nextOffset}if(!stopped){setProjects(rows);setNext(nextOffset);setError('')}}catch{if(!stopped)setError('Live updates are delayed. Your last loaded projects remain visible.')}finally{lock.current=false}}const timer=setInterval(refresh,15000);document.addEventListener('visibilitychange',refresh);window.addEventListener('focus',refresh);void refresh();return()=>{stopped=true;clearInterval(timer);document.removeEventListener('visibilitychange',refresh);window.removeEventListener('focus',refresh)}},[clientId,active])
 return <div><p>Projects from this client’s associated templates. Library updates automatically when production is marked completed. Reopening a project moves it back to Production.</p>{error&&<p role="alert" className="portal-error">{error}</p>}{!loaded?(error?<button onClick={()=>load()}>Retry</button>:<SkeletonRows count={2}/>):<>{!projects.length&&<div className="portal-empty">No associated projects yet. Link production templates in the Templates tab.</div>}{projects.map(p=><ProjectEditor key={p.id} project={p} clientId={clientId}/>)}{next!==null&&<button disabled={loading} onClick={()=>load(next)}>{loading?'Loading…':'Load more projects'}</button>}</>}</div>
}
function ProjectEditor({project:p,clientId}:{project:Project;clientId:string}){
 const {busy,saved,error,message,run}=usePortalAction();const [review,setReview]=useState(p.review_url||''),[ready,setReady]=useState(p.review_ready),[url,setUrl]=useState(p.publication_url||'')
 return <details className="portal-project-editor"><summary><span><strong>{p.title}</strong><small>{p.format} · Planned {p.release_date}</small></span><span className="portal-badge">{p.published_at?'Completed · In Library':'In production'}</span></summary><form onSubmit={e=>{e.preventDefault();run(async()=>{await request(clientId,{client_id:clientId,id:p.id,review_url:review,review_ready:ready,publication_url:url})},'Project links saved.')}}><fieldset disabled={busy} style={{border:0,padding:0,margin:0}}><label>Frame.io review link<input type="url" value={review} onChange={e=>setReview(e.target.value)} placeholder="https://…frame.io/…" maxLength={2048} required={ready}/></label><label className="portal-project-check"><input type="checkbox" checked={ready} onChange={e=>setReady(e.target.checked)}/> Ready for client review</label><p>Completion follows the production app automatically. No separate confirmation is needed here.</p><label>Published content link (optional)<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://youtube.com/watch?…" maxLength={2048}/></label>{error&&<p className="portal-error" role="alert">{error}</p>}{message&&<p className="portal-success" role="status">{message}</p>}<button className="portal-primary" disabled={busy}><ActionLabel busy={busy} saved={saved}>Save project</ActionLabel></button></fieldset></form></details>
}
