'use client'
import {useEffect,useState} from 'react'
import {ActionLabel,SkeletonRows,usePortalAction} from './portal-ux'
type Project={id:string;title:string;format:string;release_date:string;review_url:string|null;review_ready:boolean;publication_url:string|null;published_at:string|null;status:string}
async function request(clientId:string,body?:unknown,offset=0){const r=await fetch('/api/portal/admin/production?client_id='+encodeURIComponent(clientId)+'&offset='+offset,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load projects.');return d}
export default function ProjectSettings({clientId}:{clientId:string}){
 const [projects,setProjects]=useState<Project[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[next,setNext]=useState<number|null>(null),[loading,setLoading]=useState(false)
 async function load(offset=0){setLoading(true);setError('');try{const d=await request(clientId,undefined,offset);setProjects(p=>offset?[...p,...d.projects]:d.projects);setNext(d.nextOffset);setLoaded(true)}catch(e){setError(e instanceof Error?e.message:'Unable to load projects.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[clientId])
 return <div><p>Projects from this client’s associated templates. Publication is confirmed separately from internal completion.</p>{error&&<p role="alert" className="portal-error">{error}</p>}{!loaded?(error?<button onClick={()=>load()}>Retry</button>:<SkeletonRows count={2}/>):<>{!projects.length&&<div className="portal-empty">No associated projects yet. Link production templates in the Templates tab.</div>}{projects.map(p=><ProjectEditor key={p.id} project={p} clientId={clientId}/>)}{next!==null&&<button disabled={loading} onClick={()=>load(next)}>{loading?'Loading…':'Load more projects'}</button>}</>}</div>
}
function ProjectEditor({project:p,clientId}:{project:Project;clientId:string}){
 const {busy,saved,error,message,run}=usePortalAction();const [savedPublished,setSavedPublished]=useState(!!p.published_at);const [review,setReview]=useState(p.review_url||''),[ready,setReady]=useState(p.review_ready),[published,setPublished]=useState(!!p.published_at),[date,setDate]=useState(p.published_at?.slice(0,10)||''),[url,setUrl]=useState(p.publication_url||'')
 return <details className="portal-project-editor"><summary><span><strong>{p.title}</strong><small>{p.format} · Planned {p.release_date}</small></span><span className="portal-badge">{savedPublished?'Published':'Not published'}</span></summary><form onSubmit={e=>{e.preventDefault();run(async()=>{await request(clientId,{client_id:clientId,id:p.id,review_url:review,review_ready:ready,publication_url:url,published,published_at:date});setSavedPublished(published)},'Project visibility saved.')}}><fieldset disabled={busy} style={{border:0,padding:0,margin:0}}><label>Frame.io review link<input type="url" value={review} onChange={e=>setReview(e.target.value)} placeholder="https://…frame.io/…" maxLength={2048} required={ready}/></label><label className="portal-project-check"><input type="checkbox" checked={ready} onChange={e=>setReady(e.target.checked)}/> Ready for client review</label><label className="portal-project-check"><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/> Content is published · show in the client’s Library</label>{published&&<div className="portal-project-fields"><label>Actual publication date<input type="date" required max={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Published content link (optional)<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://youtube.com/watch?…" maxLength={2048}/></label></div>}{error&&<p className="portal-error" role="alert">{error}</p>}{message&&<p className="portal-success" role="status">{message}</p>}<button className="portal-primary" disabled={busy}><ActionLabel busy={busy} saved={saved}>Save project</ActionLabel></button></fieldset></form></details>
}
