const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');const {PGlite}=require('@electric-sql/pglite');
function load(file,imports={}){const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:mod.exports,require:n=>imports[n]||require(n),Buffer,process,Date,Intl,File,URL,URLSearchParams});return mod.exports}
const core=load('lib/portal/core.ts');const manual=load('lib/portal/manual.ts',{'./core':core,'./store':{}});const valid={doc_number:'OLD-1',invoice_date:'2025-01-01',total:'100.50',balance:'0',currency:'USD'};
test('manual invoice validates money, dates and currencies',()=>{assert.equal(manual.manualFields(valid).total,100.5);for(const change of [{total:'-1'},{balance:'101'},{total:'0'},{total:'1.234'},{invoice_date:'2025-02-30'},{currency:'ZZZ'},{doc_number:''}])assert.throws(()=>manual.manualFields({...valid,...change}));assert.equal(manual.manualFields({...valid,balance:'50'}).balance,50)});
test('download requires invoice ownership and does not sign a missing record',async()=>{let signed=false;const filters=[];const q={select(){return q},eq(...args){filters.push(args);return q},is(){return q},maybeSingle:async()=>({data:null})};const m=load('lib/portal/manual.ts',{'./core':core,'./store':{check:()=>{},db:()=>({from:()=>q,storage:{from:()=>({createSignedUrl:()=>{signed=true}})}})}});await assert.rejects(m.manualDownload('account-a','00000000-0000-4000-8000-000000000001'),e=>e.status===404);assert.ok(filters.some(([k,v])=>k==='account_id'&&v==='account-a'));assert.equal(signed,false)});
test('manual migration is repeatable, private, duplicate-safe and independent of QBO snapshots',async()=>{const db=new PGlite();try{await db.exec('create role anon;create role authenticated;create role service_role;create table clients(id uuid primary key);create table users(id uuid primary key);create schema storage;create table storage.objects(bucket_id text);create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);');await db.exec(fs.readFileSync('supabase/migration_creator_portal.sql','utf8'));await db.exec(fs.readFileSync('supabase/migration_portal_scoped_connections.sql','utf8'));const sql=fs.readFileSync('supabase/migration_portal_manual_invoices.sql','utf8');await db.exec(sql);await db.exec(sql);const attachments=fs.readFileSync('supabase/migration_portal_manual_attachments.sql','utf8');await db.exec(attachments);await db.exec(attachments);assert.deepEqual((await db.query('select allowed_mime_types from storage.buckets')).rows[0].allowed_mime_types,['application/pdf','image/jpeg','image/png']);const id='00000000-0000-4000-8000-000000000001';await db.query('insert into clients values($1);',[id]);await db.query('insert into users values($1)',[id]);const account=(await db.query('insert into portal_accounts(client_id) values($1) returning id',[id])).rows[0].id;const insert="insert into portal_manual_invoices(account_id,doc_number,invoice_date,currency,total,balance,storage_path,file_hash,created_by) values($1,'OLD-1','2025-01-01','USD',100,0,$2,$3,$4)";await db.query(insert,[account,'one','hash1',id]);await assert.rejects(db.query(insert,[account,'two','hash2',id]));await db.query('select portal_replace_invoices($1,$2)',[account,'[]']);assert.equal((await db.query('select count(*) from portal_manual_invoices')).rows[0].count,1);assert.equal((await db.query('select public from storage.buckets')).rows[0].public,false);await db.exec('set role authenticated');await assert.rejects(db.query('select * from portal_manual_invoices'));await db.exec('reset role');}finally{await db.close()}});

test('attachment formats use bytes, reject unsupported and oversized files',()=>{assert.equal(manual.attachmentType(Buffer.from('%PDF-1.7\n%%EOF')).extension,'pdf');assert.equal(manual.attachmentType(Buffer.from([255,216,255,224,255,217])).extension,'jpg');assert.equal(manual.attachmentType(Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0,73,69,78,68,174,66,96,130])).extension,'png');for(const bytes of [Buffer.from('<svg/>'),Buffer.from('not a jpg'),Buffer.alloc(3145729),Buffer.from('%PDF-truncated')])assert.throws(()=>manual.attachmentType(bytes))});
test('failed attachment replacement removes new object and preserves prior file',async()=>{
 const account='00000000-0000-4000-8000-000000000001',id='00000000-0000-4000-8000-000000000002',removed=[],uploaded=[];let call=0;
 const db=()=>({from(){const response=[{data:{id:account}},{data:{storage_path:'old.pdf'}},{data:null,error:{code:'23505'}}][call++];const q={select(){return q},eq(){return q},is(){return q},update(){return q},maybeSingle:async()=>response};return q},storage:{from:()=>({upload:async(path)=>{uploaded.push(path);return {}},remove:async(paths)=>{removed.push(...paths);return {}}})}});
 const m=load('lib/portal/manual.ts',{'./core':{...core,qboScope:()=> 'scope'},'./store':{db,check:e=>{if(e)throw e}}});
 const form=new FormData();for(const [k,v] of Object.entries({...valid,account_id:account,id}))form.set(k,v);form.set('file',new File(['%PDF-1.7\n%%EOF'],'new.pdf',{type:'application/pdf'}));
 await assert.rejects(m.replaceManual(form),e=>e.status===409);assert.equal(uploaded.length,1);assert.deepEqual(removed,uploaded);assert.ok(!removed.includes('old.pdf'));
});
