const {test}=require('node:test');const assert=require('node:assert/strict');const ts=require('typescript');const vm=require('node:vm');const fs=require('node:fs');
function load(file,imports){const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:mod.exports,require:n=>imports[n]||require(n),process,Buffer,Date,URL});return mod.exports}
const core=load('lib/portal/core.ts',{});
function fixture(responses,authUser){const calls=[];const client={from(table){calls.push(['from',table]);const q={};for(const method of ['select','eq','gt','delete'])q[method]=(...args)=>{calls.push([method,...args]);return q};for(const method of ['single','maybeSingle'])q[method]=async()=>responses.shift();return q}};const store=load('lib/portal/store.ts',{'./core':core,'@/lib/supabase/admin':{createAdminClient:()=>client},'@/lib/supabase/server':{},'@supabase/supabase-js':{createClient:()=>({auth:{getUser:async()=>({data:{user:authUser},error:null})}})}});return {store,calls}}
process.env.PORTAL_AUTH_URL='https://creator.example';process.env.NEXT_PUBLIC_SUPABASE_URL='https://staff.example';process.env.PORTAL_AUTH_ANON_KEY='public';
const req=token=>({headers:{get:()=>token?'Bearer '+token:null}});
test('missing and unmapped creator tokens rejected',async()=>{const f=fixture([],null);await assert.rejects(f.store.creator(req('')),e=>e.status===401);await assert.rejects(f.store.creator(req('bad')),e=>e.status===401);const g=fixture([{data:null,error:null}],{id:'unknown'});await assert.rejects(g.store.creator(req('valid')),e=>e.status===403)});
test('creator account selected only from authenticated identity and enabled mapping',async()=>{const f=fixture([{data:{id:'account-a'},error:null},{data:{id:'account-a',enabled:true},error:null}],{id:'creator-a'});assert.equal((await f.store.creator(req('valid'))).account.id,'account-a');assert.ok(f.calls.some(c=>c[0]==='eq'&&c[1]==='creator_user_id'&&c[2]==='creator-a'));assert.ok(f.calls.some(c=>c[0]==='eq'&&c[1]==='id'&&c[2]==='account-a'));assert.ok(f.calls.filter(c=>c[0]==='eq'&&c[1]==='enabled'&&c[2]===true).length===2)});
test('preview rechecks staff active status on every read',async()=>{const f=fixture([{data:{staff_id:'staff-a',account_id:'account-a'},error:null},{data:{role:'ops_manager',active:false},error:null}],null);await assert.rejects(f.store.creator(req('preview_ticket')),e=>e.status===403)});
