const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');
test('independent clients preserve account ownership; templates can be assigned atomically and removed without billing loss',async()=>{
const db=new PGlite();try{
await db.exec('create role anon;create role authenticated;create role service_role;create table clients(id uuid primary key,label text);create table users(id uuid primary key);create table task_templates(id uuid primary key,client_id uuid references clients(id),template_name text);');
await db.exec(fs.readFileSync('supabase/migration_creator_portal.sql','utf8'));await db.exec(fs.readFileSync('supabase/migration_portal_scoped_connections.sql','utf8'));
const c='00000000-0000-4000-8000-000000000001',p='00000000-0000-4000-8000-000000000002',t='00000000-0000-4000-8000-000000000003';await db.query("insert into clients values($1,'Walker'),($2,'Internal')",[c,p]);const a=(await db.query('insert into portal_accounts(client_id,enabled) values($1,true) returning id',[c])).rows[0].id;await db.query('select portal_replace_invoices($1,$2)',[a,JSON.stringify([{qbo_id:'1',currency:'USD',total:10,balance:0,source_updated_at:'2026-09-01T00:00:00Z'}])]);await db.query("insert into task_templates values($1,$2,'Podcast')",[t,p]);
const sql=fs.readFileSync('supabase/migration_portal_clients.sql','utf8');await db.exec(sql);await db.exec(sql);
assert.equal((await db.query('select count(*) from portal_clients')).rows[0].count,1);assert.equal((await db.query('select id,enabled from portal_accounts')).rows[0].id,a);assert.equal((await db.query('select enabled from portal_accounts')).rows[0].enabled,true);assert.equal((await db.query('select count(*) from portal_client_templates')).rows[0].count,0);
const other=(await db.query("insert into portal_clients(label) values('Other') returning id")).rows[0].id;const selection=JSON.stringify([{production_client_id:p,template_name:'Podcast'}]);await db.query('select portal_assign_templates($1,$2)',[c,selection]);await assert.rejects(db.query('select portal_assign_templates($1,$2)',[other,selection]));assert.equal((await db.query('select portal_client_id from portal_client_templates')).rows[0].portal_client_id,c);
await assert.rejects(db.query('select portal_assign_templates($1,$2)',[c,JSON.stringify([{production_client_id:p,template_name:'Missing'}])]));assert.equal((await db.query('select count(*) from portal_client_templates')).rows[0].count,1);
await db.query('select portal_set_client_active($1,false)',[c]);assert.equal((await db.query('select enabled from portal_accounts')).rows[0].enabled,false);await assert.rejects(db.query('update portal_accounts set enabled=true where id=$1',[a]));await db.query('select portal_set_client_active($1,true)',[c]);assert.equal((await db.query('select enabled from portal_accounts')).rows[0].enabled,false);
await db.query('delete from task_templates where id=$1',[t]);assert.equal((await db.query('select count(*) from portal_client_templates')).rows[0].count,0);await db.query('delete from clients where id=$1',[c]);assert.equal((await db.query('select count(*) from portal_clients where id=$1',[c])).rows[0].count,1);assert.equal((await db.query('select count(*) from portal_invoices')).rows[0].count,1);
await db.exec('set role authenticated');await assert.rejects(db.query('select * from portal_clients'));await assert.rejects(db.query('select portal_set_client_active($1,false)',[c]));await db.exec('reset role');
}finally{await db.close()}});
