'use client'
import {useEffect,useState} from 'react'
import {Toggle} from './Toggle'
export type Brief={open:boolean;topic:string;guest:string;description:string;duration:number;deadline:string}
export function SponsorshipBrief({clientId,template,releaseDate,onChange,onStatus}:{clientId:string;template:string;releaseDate:string;onChange:(brief:Brief|null)=>void;onStatus:(ready:boolean)=>void}){
 const [state,setState]=useState<'loading'|'off'|'on'|'error'>('loading'),[attempt,setAttempt]=useState(0)
 const [value,setValue]=useState<Brief>({open:false,topic:'',guest:'',description:'',duration:60,deadline:''})
 useEffect(()=>{let current=true;setState('loading');onStatus(false);onChange(null)
 fetch('/api/portal/admin/project-sponsorship?client_id='+encodeURIComponent(clientId)+'&template='+encodeURIComponent(template)).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d}).then(d=>{if(!current)return;setState(d.enrolled?'on':'off');const initial={open:d.open_by_default===true,topic:'',guest:'',description:'',duration:60,deadline:''};setValue(initial);onChange(d.enrolled?initial:null);onStatus(true)}).catch(()=>{if(current)setState('error')})
 return()=>{current=false}
 },[clientId,template,attempt])
 const update=(patch:Partial<Brief>)=>{const next={...value,...patch};setValue(next);onChange(next)}
 if(state==='off')return null
 if(state==='loading')return <p role="status" className="text-sm text-neutral-400">Checking Content NASCAR participation…</p>
 if(state==='error')return <div role="alert">Could not check sponsorship settings. <button type="button" onClick={()=>setAttempt(v=>v+1)}>Retry</button></div>
 return <section className="rounded-xl border border-orange-900/50 p-5 space-y-4"><h2 className="text-lg font-bold">Content NASCAR</h2><p className="text-sm text-neutral-400">This brief appears in the creator’s Sponsorships page. Title and release date come from this project. Nilli reviews it before sharing with brands.</p><label className="flex items-center gap-3"><Toggle checked={value.open} onChange={e=>update({open:e.target.checked})}/> Open this episode for sponsorship requests</label><p className="text-xs text-neutral-400">Uses the creator’s default; you can change it for this episode. Brand requests still require creator acceptance.</p><label className="block">Topic<input className="block w-full rounded bg-black border border-neutral-700 p-2 mt-1" required maxLength={200} value={value.topic} onChange={e=>update({topic:e.target.value})}/></label><label className="block">Guest (optional)<input className="block w-full rounded bg-black border border-neutral-700 p-2 mt-1" maxLength={160} value={value.guest} onChange={e=>update({guest:e.target.value})}/></label><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label>Estimated duration (minutes)<input className="block w-full rounded bg-black border border-neutral-700 p-2 mt-1" type="number" min={1} max={1440} required value={value.duration} onChange={e=>update({duration:Number(e.target.value)})}/></label><label>Requests accepted until<input className="block w-full rounded bg-black border border-neutral-700 p-2 mt-1" type="date" max={releaseDate.slice(0,10)} required value={value.deadline} onChange={e=>update({deadline:e.target.value})}/></label></div><label className="block">Why this episode is attractive to brands<textarea className="block w-full rounded bg-black border border-neutral-700 p-2 mt-1" required rows={3} maxLength={4000} value={value.description} onChange={e=>update({description:e.target.value})}/></label></section>
}
