import { check, db, locked } from './store'
import { decrypt, encrypt, normalizeInvoice, PortalError, required } from './core'
type Tokens={access_token:string;refresh_token:string;expires_in:number}
function apiBase(){const mode=required('QBO_ENVIRONMENT');if(!['sandbox','production'].includes(mode))throw new PortalError(503,'Invalid QuickBooks environment.');return mode==='sandbox'?'https://sandbox-quickbooks.api.intuit.com':'https://quickbooks.api.intuit.com'}
export async function grant(params:URLSearchParams):Promise<Tokens>{const r=await fetch('https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer',{method:'POST',headers:{Authorization:'Basic '+Buffer.from(required('QBO_CLIENT_ID')+':'+required('QBO_CLIENT_SECRET')).toString('base64'),'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body:params,signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok)throw new PortalError(502,'QuickBooks authorization failed. Reconnect if the problem persists.');const t=await r.json();if(!t.access_token||!t.refresh_token||!Number.isFinite(t.expires_in))throw new PortalError(502,'Invalid QuickBooks token response.');return t}
// All callers hold the database lock: rotating refresh tokens cannot race.
async function connection(){const {data,error}=await db().from('portal_qbo').select('*').eq('id',true).single();check(error);if(!data)throw new PortalError(503,'Connect QuickBooks first.');if(data.realm_id!==required('QBO_EXPECTED_REALM_ID'))throw new PortalError(503,'QuickBooks company does not match configuration.');let tokens=decrypt<Tokens>(data.encrypted_tokens);if(Date.parse(data.access_expires_at)<Date.now()+60000){tokens=await grant(new URLSearchParams({grant_type:'refresh_token',refresh_token:tokens.refresh_token}));const {error:e}=await db().from('portal_qbo').update({encrypted_tokens:encrypt(tokens),access_expires_at:new Date(Date.now()+tokens.expires_in*1000).toISOString()}).eq('id',true);check(e)}return {...data,tokens}}
async function qbo(c:Awaited<ReturnType<typeof connection>>,path:string,pdf=false){const r=await fetch(`${apiBase()}/v3/company/${encodeURIComponent(c.realm_id)}/${path}`,{headers:{Authorization:'Bearer '+c.tokens.access_token,Accept:pdf?'application/pdf':'application/json'},signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok)throw new PortalError(502,r.status===429?'QuickBooks rate limit reached. A later sync will retry.':'QuickBooks request failed. A later sync will retry.');return r}
export async function connectQbo(code:string,realm:string){if(realm!==required('QBO_EXPECTED_REALM_ID'))throw new PortalError(400,'The selected QuickBooks company does not match Nilli’s configured company.');return locked(async()=>{const t=await grant(new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:required('QBO_REDIRECT_URI')}));const {error}=await db().from('portal_qbo').upsert({id:true,realm_id:realm,encrypted_tokens:encrypt(t),access_expires_at:new Date(Date.now()+t.expires_in*1000).toISOString(),last_error:null,dirty_version:1,synced_version:0});check(error)})}
export async function syncInvoices(){return locked(async()=>{
 try {const c=await connection();const start=Date.now();const {data:accounts,error}=await db().from('portal_accounts').select('id,qbo_customer_id').eq('enabled',true).not('qbo_customer_id','is',null);check(error);let count=0;
 for(const a of accounts||[]){if(!/^\d+$/.test(a.qbo_customer_id))throw new PortalError(400,'QuickBooks customer mapping is invalid.');const rows=[];for(let position=1;;position+=100){if(Date.now()-start>180000)throw new PortalError(503,'Sync needs a smaller batch. Completed accounts were saved; remaining accounts will retry.');const query=`select * from Invoice where CustomerRef = '${a.qbo_customer_id}' startposition ${position} maxresults 100`;const body=await(await qbo(c,'query?query='+encodeURIComponent(query))).json();if(!body.QueryResponse)throw new PortalError(502,'QuickBooks invoice response is incomplete.');const page=body.QueryResponse.Invoice||[];for(const i of page){if(i.CustomerRef?.value!==a.qbo_customer_id)throw new PortalError(502,'QuickBooks customer mismatch.');rows.push(normalizeInvoice(i))}if(page.length<100)break}
 const {error:e}=await db().rpc('portal_replace_invoices',{target_account:a.id,rows_json:rows});check(e);count+=rows.length;
 }
 const {error:e}=await db().from('portal_qbo').update({last_success_at:new Date().toISOString(),last_error:null,synced_version:c.dirty_version}).eq('id',true);check(e);
 await db().from('portal_tokens').delete().lt('expires_at',new Date().toISOString());return {accounts:accounts?.length||0,invoices:count};
 }catch(e){await db().from('portal_qbo').update({last_error:e instanceof PortalError?e.message:'Synchronization interrupted. Retry pending.'}).eq('id',true);throw e}
 })}
export async function invoicePdf(accountId:string,invoiceId:string){return locked(async()=>{const {data,error}=await db().from('portal_invoices').select('qbo_id').eq('account_id',accountId).eq('qbo_id',invoiceId).maybeSingle();check(error);if(!data)throw new PortalError(404,'Invoice not found.');const {data:a,error:ae}=await db().from('portal_accounts').select('qbo_customer_id').eq('id',accountId).single();check(ae);const c=await connection();const current=await(await qbo(c,'invoice/'+encodeURIComponent(invoiceId))).json();if(current.Invoice?.CustomerRef?.value!==a?.qbo_customer_id)throw new PortalError(404,'Invoice no longer belongs to this account.');const r=await qbo(c,'invoice/'+encodeURIComponent(invoiceId)+'/pdf',true);return new Uint8Array(await r.arrayBuffer())})}
